# Generated by Django 4.2.4 on 2023-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.CharField(max_length=100)),
                ('Product_quantity', models.IntegerField()),
            ],
        ),
    ]
